name: shirah
description: "SHIRAH - A Business & Community Super App for Bangladesh. Features digital services, product reselling, micro jobs, reward points, community posts, and wallet system."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

#---------------------- PACKAGES----------------------#
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase packages
  firebase_core: ^3.13.0
  firebase_auth: ^5.6.4
  cloud_firestore: ^5.6.6
  firebase_database: ^11.3.5
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5

  # Authentication
  google_sign_in: ^6.2.2

  # Utility packages
  http: ^1.4.0
  intl: ^0.20.2
  logger: ^2.6.1
  url_launcher: ^6.1.12
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  permission_handler: ^11.0.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^5.0.1
  webview_flutter: ^4.13.0
  share_plus: ^10.1.4

  # Loaders and Animations
  lottie: ^3.3.2
  shimmer: ^3.0.0
  flutter_easyloading: ^3.0.5

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # Animated Emoji for reactions
  animated_emoji: ^3.2.1

  # State Management and Storage
  get: ^4.6.1
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4

  # Fonts (Google Fonts - Optional)
  google_fonts: ^6.2.1
  cloud_functions: ^5.6.2

  # App Configuration
  # flutter_launcher_icons: ^0.14.4
  # rename_app: ^1.6.5



#---------------------- ./ PACKAGES END ----------------------#



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # change_app_package_name: ^1.5.0


# flutter_launcher_icons:
#   android: true
#   ios: true

#   image_path: assets/images/logo.png

#   adaptive_icon_foreground: assets/images/logo.png
#   adaptive_icon_background: "#000000" # or any brand color
#   min_sdk_android: 21

#   -> flutter pub get
#   -> dart run flutter_launcher_icons


flutter:

  uses-material-design: true

  #---------------------- LOCAL ASSETS ----------------------#
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/svg/
    - assets/images/






  #---------------------- LOCAL FONTS ----------------------#
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Italic.ttf
  #         weight: 400
  #         style: italic
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700